name : Deploy Github Pages

on:
 push:
   branches :
        -main
permissions :
  contents : read
  pages : write
  id-token: write
jobs :
  deploy :
    runs-on: ubuntu-latest
    steps :
      -uses :actions/checkout@v4

      -name : setup pages
      -uses :actions/configure-pages@v4

      -name : Upload artifacts
      uses : actions/upload-pages-artifacts@v4
      with : 
        path :
      -name : Deploy
      -uses : actions/deploy-pages@v4
